# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: emozes/dream:latest
        file: Dockerfile
#     - name: Test with pytest
#       run: |
#         docker run your_docker_hub_username/your_docker_image_name:latest pytest

      # - name: Terraform Apply
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 1.0.7 # Replace with the version of Terraform you want to use
      #   env:
      #     TF_BACKEND_CONFIG: "configs/main.tf" # Replace with your Terraform backend configuration
      #   run: |
      #     terraform init
      #     terraform plan
